==========================================
SLURM_JOB_ID = 16579317
SLURM_JOB_NODELIST = d13-09
TMPDIR = /tmp/SLURM_16579317
==========================================
wandb: Currently logged in as: hale-akrami (usc_akrami). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.9
wandb: Run data is saved locally in /project/ajoshi_27/akrami/3D_lesion_DF/wandb/run-20230903_114450-9gmijlwb
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run half_res
wandb: ‚≠êÔ∏è View project at https://wandb.ai/usc_akrami/33_ddpm
wandb: üöÄ View run at https://wandb.ai/usc_akrami/33_ddpm/runs/9gmijlwb
2023-09-03 11:45:03,186 - A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "/project/ajoshi_27/akrami/3D_lesion_DF/3d_ddpm.py", line 169, in <module>
    n_epochs = cfg.get('n_epochs',100)
NameError: name 'cfg' is not defined
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.004 MB of 0.004 MB uploaded (0.000 MB deduped)wandb: \ 0.004 MB of 0.017 MB uploaded (0.000 MB deduped)wandb: | 0.017 MB of 0.017 MB uploaded (0.000 MB deduped)wandb: üöÄ View run half_res at: https://wandb.ai/usc_akrami/33_ddpm/runs/9gmijlwb
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230903_114450-9gmijlwb/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 256, in check_network_status
    self._loop_check_status(
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 212, in _loop_check_status
    local_handle = request()
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 864, in deliver_network_status
    return self._deliver_network_status(status)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 610, in _deliver_network_status
    return self._deliver_record(record)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 569, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
